# Runs `cargo update` periodically.

name: Update Dependencies

on:
  # schedule:
  # Run weekly
  # - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    if: github.repository == 'paradigmxyz/revmc'
    uses: tempoxyz/ci/.github/workflows/cargo-update-pr.yml@934b6a6317ac26272eaecf0d265472f4105c99d6 # main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
